name: Run Sweep Fees if new input data is there

on:
  pull_request:
    types: [ labeled ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  sweepFees:
    if: github.event.label.name == 'Sweep Fees'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tools/python
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: print working dir
      run: pwd

    - name: Install Requirements
      run: pip install -r requirements.txt

    - name: Run Sweep
      run: python3 sweepFees.py

    - name: Commit and push changes
      uses:  stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Generate Fee Sweep transaction builder jsons
        commit_user_name:  GitHub Actions
        commit_user_email: github-actions[bot]@users.noreply.github.com
        commit_author: Github Actions <noreply@users.noreply.github.com>